FROM {{ web_image }}:{{ awx_version }}
USER 0
RUN sudo yum -y remove nginx
USER root

# Need gcc and devel libraries to build ansible and deps
RUN yum -y install gcc libffi-devel libxml2-devel libxml2-python libxslt-devel openssl-devel python-devel

# Add a script to activate the ansible virtual environment and to install more modules
ADD venv_ansible_modules.sh /usr/bin/venv_ansible_modules.sh
RUN chmod +x /usr/bin/venv_ansible_modules.sh
RUN /usr/bin/venv_ansible_modules.sh

# Fetch the Azure preview modules for most up-to-date functionality
RUN git clone https://github.com/Azure/azure_preview_modules.git /var/lib/awx/azure_preview_modules

# Copy the modules over the top of the included Ansible modules

# For the ansible in the virtual env (not working)
#RUN cp -f /var/lib/awx/azure_preview_modules/library/* /var/lib/awx/venv/ansible/lib/python2.7/site-packages/ansible/modules/cloud/azure/ && \
#    cp -f /var/lib/awx/azure_preview_modules/module_utils/* /var/lib/awx/venv/ansible/lib/python2.7/site-packages/ansible/module_utils/

# For the system ansible
RUN cp -f /var/lib/awx/azure_preview_modules/library/* /usr/lib/python2.7/site-packages/ansible/modules/cloud/azure/ && \
    cp -f /var/lib/awx/azure_preview_modules/module_utils/* /usr/lib/python2.7/site-packages/ansible/module_utils/

RUN sed -i "/{{ '{{' }} scm_result is defined|ternary('--force',omit) {{ '}}' }}/c\        command: ansible-galaxy install -r requirements.yml -p {{ '{{' }}project_path|quote{{ '}}' }}/roles/" /usr/lib/python2.7/site-packages/awx/playbooks/project_update.yml
USER 1000
EXPOSE 8052
CMD /usr/bin/launch_awx_task.sh
